[pytest]
addopts = --maxfail=2 -rf -v
log_cli = true
log_cli_level = INFO
log_file = logs/saucelabs.log
log_file_level = DEBUG
log_file_mode = w
log_format = %(asctime)s [%(levelname)s] %(name)s - %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
testpaths = tests
strict_config = true
strict_markers = true
strict_parametrization_ids = true
strict_xfail = true

markers =
    smoke: means fast smoke tests.
    regression: tests for regression suite.
    login: login related tests.
    tcid: test case ID marker.
