# pytest.ini

[pytest]
addopts = -s --strict-markers
log_cli = true

markers =
    smoke: means fast smoke tests.
    regression: tests for regression suite.
    login: login related tests.
    tcid: test case ID marker.
